feat(repository): add “defaultFn” property decorator
sourcefuse/loopback4-sequelize pull request #40
Opened 2023-06-14 13:53 UTC by RaghavaroraSF

## Description
- Added “defaultFn” property decorator

Fixes #9597

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-18 17:01 UTC, shubhamp-sf requested changes
Also write some tests cases to cover your changes.

2023-06-18 17:01 UTC, shubhamp-sf commented on src/sequelize/sequelize.repository.base.ts
> +        definition[propName]['defaultFn'] = defaultValue;
Don't override the loopback definition, use a new variable instead.

2023-06-19 10:45 UTC, RaghavaroraSF commented on src/sequelize/sequelize.repository.base.ts
> +        definition[propName]['defaultFn'] = defaultValue;
done

2023-06-19 10:45 UTC, RaghavaroraSF commented on src/sequelize/sequelize.repository.base.ts
> +            defaultValue = nanoid(9);
done

2023-06-19 10:45 UTC, RaghavaroraSF commented on src/sequelize/sequelize.repository.base.ts
> +            defaultValue = uuid.v4();
done

2023-06-22 09:09 UTC, shubhamp-sf requested changes

2023-06-22 09:09 UTC, shubhamp-sf commented on src/__tests__/integration/repository.integration.ts
> +      const firstUser = await categoryRepo.create(userWithId);
You're testing out `defaultFn`, so the property which has this defined (`name` in this case) shouldn't be specified while creating.

2023-06-22 09:09 UTC, shubhamp-sf commented on src/__tests__/integration/repository.integration.ts
> +      const dateObject = new Date(firstUser.name);
Also change the column name storing date in `name` column doesn't make sense even if it's just a test case.

2023-06-22 09:09 UTC, shubhamp-sf commented on src/__tests__/integration/repository.integration.ts
> +      expect(_.isDate(dateObject)).to.be.true;
It'll never execute, true must be a function here.

2023-06-22 09:09 UTC, shubhamp-sf commented on src/__tests__/integration/repository.integration.ts
> +    });
Similar changes for this don't specify the prop on which `defaultFn` is used. It's not a valid test cases.

2023-06-27 07:06 UTC, shubhamp-sf requested changes

2023-06-27 07:19 UTC, RaghavaroraSF commented on src/sequelize/sequelize.repository.base.ts
> +            break;
done

2023-06-27 07:19 UTC, RaghavaroraSF commented on src/sequelize/sequelize.repository.base.ts
> +            defaultValue = null; // Or any other default value
done

2023-06-27 08:43 UTC, RaghavaroraSF commented on src/__tests__/integration/repository.integration.ts
> +    });
done

2023-06-27 12:27 UTC, shubhamp-sf approved these changes

2023-06-29 16:49 UTC, merged